version: '3.7'

services:
  django_guni_serv:
    build:
      context: .
    volumes:
      - static:/static
    depends_on:
      - pg_db
  
  nginx_serv:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_guni_serv
  
  pg_db:
    image: postgres
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbms
    expose:
      - "5432"


volumes:
  static:

