# Generated by Django 3.2.3 on 2021-05-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=122)),
                ('lname', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122)),
                ('phone', models.IntegerField(max_length=10)),
                ('addr', models.CharField(max_length=122)),
                ('desc', models.CharField(max_length=222)),
                ('city', models.CharField(max_length=122)),
                ('state', models.CharField(max_length=122)),
                ('zip', models.CharField(max_length=6)),
                ('date', models.DateField()),
            ],
        ),
    ]
